### ISSUE TITLE
Field name is not showing for "SignUp" view

### ISSUE THREAD

**Issue by yousudip** [ipragmatech/Amazon-Cognito-Custom-SignIn-UI#1]
I had made the "Create New Account" and "Forgot your password?" links in the "UserPoolSignInView" class. But when the "SignUp" view is loaded, there is no field name showing in the Sign Up form. Is is some style issue? If it is then how do I fix this?

SignIn View | SignUp View
------------ | -------------
![image](https://user-images.githubusercontent.com/11506803/41516178-ce71ba50-72d0-11e8-8ce0-a0d5469a9366.png)|![image](https://user-images.githubusercontent.com/11506803/41516209-f7f0d2e4-72d0-11e8-8084-0f6ea6338f3e.png)

**Comment by sinhadeepak** [comment]
In our sample solution, we are using default form for Signup and have not customized the Signup form. 
We have, however, overridden SignIn View in the sample app. While generating the SignIn FormView, we provide the hint as 3rd parameter to the function addFormField.

Please refer to the call
_credentialsFormView.addFormField(context,
                InputType.TYPE_CLASS_TEXT| InputType.TYPE_TEXT_VARIATION_PASSWORD,
                context.getString(com.amazonaws.mobile.auth.userpools.R.string.sign_in_password));_
in UserPoolSignIn.java

If you are overriding  SignUp form in your app, you should pass the hint as the 3rd parameter. This hint value can be retrieved either from the Strings file or can be provided directly.

Please refer to the function 

_signUpForm.addFormField(getContext(),
            InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD,
            getContext().getString(R.string.sign_in_password));_

in the com.amazonaws.mobile.auth.userpools.SignUpView.java

**Comment by junym** [comment]
Hi guys, I'm newbie on dev using android aws skills. Can you point me a tutorial or an example how I can build a custom signUp screen using your code?
